version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - './:/var/www'
        depends_on:
            - db_postgres
        networks:
            - laravel
    nginx:
        image: 'nginx:alpine'
        restart: unless-stopped
        ports:
            - '8989:80'
        volumes:
            - './:/var/www'
            - './docker/nginx/:/etc/nginx/conf.d/'
        networks:
            - laravel
    db_postgres:
        image: 'postgres:latest'
        restart: unless-stopped
        environment:
            - POSTGRES_DB=database
            - POSTGRES_PASSWORD=passdb
            - POSTGRES_USER=postgres
        volumes:
            - './.docker/postgresql/data:/var/lib/postgresql/data'
        ports:
            - '5432:5432'
        networks:
            - laravel
    pgsql:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
networks:
    laravel:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
