version: "3.8"

services:
  # image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db_postgres
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db postgress
  db_postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=passdb
      - POSTGRES_USER=postgres
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
